# Generated by Django 2.1 on 2018-09-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rating_list',
        ),
        migrations.AddField(
            model_name='person',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
    ]
