# Generated by Django 2.1 on 2018-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('rating_list', models.CharField(max_length=128)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
